--- 
abstract: Client-side library for OpenResty servers
author: 
  - Agent Zhang <agentzh@yahoo.cn>
build_requires: 
  Data::Dumper: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: WWW-OpenResty
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  JSON::XS: 2.1
  LWP::UserAgent: 0
  Params::Util: 0.31
  perl: 5.6.1
version: 0.05
